window.NAVAIL_CONFIG = {
  SUPABASE_URL: 'https://ehotaizdxfhwuuitjhty.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVob3RhaXpkeGZod3V1aXRqaHR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU5OTQ1MjMsImV4cCI6MjA5MTU3MDUyM30.z2YNyQxY2_VjkaZhXfb-qKejBikOOoNXKlVcYsALglM',
  GA_MEASUREMENT_ID: 'G-D018ZYMWZE',
};
